// Generates public/lib/pinyin-table.js: toneless pinyin for every CJK Unified
// Ideograph (U+4E00–U+9FFF) using macOS's built-in Mandarin→Latin transform.
import Foundation

let first: UInt32 = 0x4E00, last: UInt32 = 0x9FFF
var readings: [String] = []
readings.reserveCapacity(Int(last - first + 1))
for cp in first...last {
    guard let scalar = Unicode.Scalar(cp) else { readings.append(""); continue }
    let s = String(Character(scalar))
    let latin = s.applyingTransform(.mandarinToLatin, reverse: false) ?? ""
    let plain = latin.applyingTransform(.stripDiacritics, reverse: false) ?? latin
    let py = plain.lowercased().filter { $0 >= "a" && $0 <= "z" }
    readings.append(py)
}
let out = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "pinyin-table.js"
let body = "// Generated by tools/gen-pinyin.swift from macOS's Mandarin-Latin transform.\n" +
    "// Toneless pinyin for U+4E00..U+9FFF, space-separated, one entry per code point.\n" +
    "export const PINYIN_FIRST = 0x4E00;\n" +
    "export const PINYIN_TABLE = \"" + readings.joined(separator: " ") + "\";\n"
try! body.write(toFile: out, atomically: true, encoding: .utf8)
print("wrote \(readings.count) readings to \(out)")
